# config/cache.yml
development:
  store: :solid_cache
  url: <%= ENV.fetch("CACHE_URL", "redis://localhost:6379/0") %>
  expires_in: <%= ENV.fetch("CACHE_EXPIRES_IN", 1.week) %>

test:
  store: :solid_cache
  url: <%= ENV.fetch("CACHE_URL", "redis://localhost:6379/0") %>
  expires_in: <%= ENV.fetch("CACHE_EXPIRES_IN", 1.week) %>

production:
  store: :solid_cache
  url: <%= ENV.fetch("CACHE_URL", "redis://localhost:6379/0") %>
  expires_in: <%= ENV.fetch("CACHE_EXPIRES_IN", 1.week) %>